create table if not exists public.game_rooms (
  id bigint generated by default as identity primary key,
  game_key text not null,
  guild_id text,
  channel_id text not null,
  channel_name text,
  enabled boolean not null default true,
  mode text,
  created_by_user_id text,
  created_by_username text,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists game_rooms_game_key_channel_id_idx
  on public.game_rooms (game_key, channel_id);

create index if not exists game_rooms_game_key_enabled_idx
  on public.game_rooms (game_key, enabled);

alter table public.game_rooms enable row level security;

create policy "service_role_full_game_rooms"
on public.game_rooms
for all
to service_role
using (true)
with check (true);
