create table if not exists public.players (
  user_id text primary key,
  username text not null,
  wallet_xu integer not null default 0,
  wallet_ngoc integer not null default 0,
  player_level integer not null default 1,
  player_xp integer not null default 0,
  profession_current text null,
  profession_xp integer not null default 0,
  profession_levels jsonb not null default '{}'::jsonb,
  stats_total_xu_earned integer not null default 0,
  stats_total_ngoc_earned integer not null default 0,
  stats_total_work_actions integer not null default 0,
  stats_total_items_sold integer not null default 0,
  cooldown_daily_at bigint not null default 0,
  cooldown_work_at bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventories (
  id bigint generated by default as identity primary key,
  user_id text not null references public.players(user_id) on delete cascade,
  item_id text not null,
  quantity integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, item_id)
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  username text not null,
  type text not null,
  changes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_transactions_user_id on public.transactions(user_id);
create index if not exists idx_transactions_created_at on public.transactions(created_at desc);

alter table public.players enable row level security;
alter table public.inventories enable row level security;
alter table public.transactions enable row level security;

create policy "service_role_full_players"
on public.players
for all
to service_role
using (true)
with check (true);

create policy "service_role_full_inventories"
on public.inventories
for all
to service_role
using (true)
with check (true);

create policy "service_role_full_transactions"
on public.transactions
for all
to service_role
using (true)
with check (true);
