module.exports = {
  river_fish: { name: "Linh Ngư", rarity: "Common", emoji: "🐟" },
  fresh_shrimp: { name: "Linh Tôm", rarity: "Uncommon", emoji: "🦐" },
  pearl_fragment: { name: "Mảnh Minh Châu", rarity: "Rare", emoji: "🫧" },
  iron_ore: { name: "Huyền Thiết Khoáng", rarity: "Common", emoji: "🪨" },
  crystal_shard: { name: "Mảnh Linh Tinh", rarity: "Uncommon", emoji: "💎" },
  silver_ore: { name: "Ngân Khoáng", rarity: "Rare", emoji: "⛓️" },
  wild_herb: { name: "Linh Thảo", rarity: "Common", emoji: "🌿" },
  forest_fiber: { name: "Sơn Tơ", rarity: "Uncommon", emoji: "🧵" },
  moon_flower: { name: "Nguyệt Hoa", rarity: "Rare", emoji: "🌸" },
  catalyst_powder: { name: "Hóa Linh Phấn", rarity: "Common", emoji: "🪄" },
  minor_elixir: { name: "Tiểu Linh Đan", rarity: "Uncommon", emoji: "🧪" },
  refined_essence: { name: "Tinh Luyện Linh Dịch", rarity: "Rare", emoji: "💠" },
  old_coin: { name: "Cổ Tiền", rarity: "Common", emoji: "🪙" },
  relic_fragment: { name: "Mảnh Cổ Bảo", rarity: "Uncommon", emoji: "🏺" },
  sealed_relic: { name: "Phong Ấn Cổ Bảo", rarity: "Rare", emoji: "📿" },
  basic_bait: { name: "Mồi Linh Câu", rarity: "Common", emoji: "🪱" },
  simple_pickaxe: { name: "Thiết Cuốc", rarity: "Uncommon", emoji: "⛏️" },
  field_kit: { name: "Sơn Dã Trang Bị", rarity: "Uncommon", emoji: "🎒" },
  jade_token: { name: "Ngọc Bài", rarity: "Rare", emoji: "🀄" },
  minor_potion: { name: "Bình Hồi Linh", rarity: "Uncommon", emoji: "🧴" },
  polished_relic: { name: "Mài Sáng Cổ Bảo", rarity: "Rare", emoji: "✨" },
  spirit_stone: { name: "Linh Thạch", rarity: "Rare", emoji: "🔷" },
  foundation_pill: { name: "Trúc Cơ Đan", rarity: "Epic", emoji: "🟣" },
  spirit_core: { name: "Kim Đan Phôi", rarity: "Legendary", emoji: "☀️" },
  bamboo_rod: { name: "Thanh Trúc Câu", rarity: "Epic", emoji: "🎣" },
  earth_hammer: { name: "Địa Chấn Chùy", rarity: "Epic", emoji: "🔨" },
  herb_satchel: { name: "Túi Bách Thảo", rarity: "Epic", emoji: "🪴" },
  flame_cauldron: { name: "Ly Hỏa Đỉnh", rarity: "Epic", emoji: "🏺" },
  relic_compass: { name: "Tầm Bảo La Bàn", rarity: "Epic", emoji: "🧭" },
  secret_manual_page: { name: "Tàn Trang Bí Kíp", rarity: "Rare", emoji: "📜" }
};
