module.exports = {
  river_fish: 10,
  fresh_shrimp: 18,
  pearl_fragment: 40,
  iron_ore: 12,
  crystal_shard: 20,
  silver_ore: 42,
  wild_herb: 9,
  forest_fiber: 14,
  moon_flower: 36,
  catalyst_powder: 11,
  minor_elixir: 22,
  refined_essence: 45,
  old_coin: 13,
  relic_fragment: 24,
  sealed_relic: 50,
  basic_bait: 8,
  simple_pickaxe: 80,
  field_kit: 70,
  jade_token: 55,
  minor_potion: 28,
  polished_relic: 60
};
